### ISSUE TITLE
Fix issue when submitting prices to the website

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/sc-trade-companion#67]
```
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
```

**Comment by EtienneLamoureux** [comment]
See https://discord.com/channels/832608007313424444/1217192814031667242/1217193283999236107

**Comment by EtienneLamoureux** [comment]
https://www.baeldung.com/spring-webflux-retry

**Comment by EtienneLamoureux** [comment]
Duplicated by #74
